### ISSUE TITLE
template api authorization check

### ISSUE THREAD

**Issue by havetisyan** [yahoo/athenz#239]
Restricting "puDomainTemplate" api

Provide specific authorization check for the template being applied:
authorize ("update", "{name}:template.{template}");

**Comment by havetisyan** [comment]
@tatyano I looked at this request but that's not possible for the putDomainTemplate API

resource DomainTemplate PUT "/domain/{name}/template"

For the put operation, the only component in the URI is the name of the domain so the authorization check can only include components from the URI.

So we can update the authorization check to be:

    authorize ("update", "{name}:template");

but nothing more specific.

For the delete operation, we have the URI as:

resource DomainTemplate DELETE "/domain/{name}/template/{template}"

so we can update the authorization check to be:

    authorize ("delete", "{name}:template.{template}");

**Comment by tatyano** [comment]
@havetisyan Thank you for your consideration.

For the delete operation, the idea sounds perfect.

For the put operation, Is it possible for you to change the interface like below?
```
resource DomainTemplate PUT "/domain/{name}/template/{templateName}"
```
If it's not , the idea you wrote seems to be the best.

Thank you,
Chris

**Comment by havetisyan** [comment]
Chris, we can't change the existing api for backward compatibility reasons but I think we should be able to add a new endpoint with specifying the template name and during next api revision (e.g. v2) remove the old one. I'll look into this.

**Comment by tatyano** [comment]
Thank you for this update. PutDomainTemplateExt is exactly the style what we wanted.
