### ISSUE TITLE
System properties "read_timeout" and "connect_timeout" in java clients are not currently working

### ISSUE THREAD

**Issue by tatyano** [yahoo/athenz#246]
The properties below are not working currently.
For example in zms client, the method setProperty [sets a property to client](https://github.com/yahoo/athenz/blob/master/clients/java/zms/src/main/java/com/yahoo/athenz/zms/ZMSRDLGeneratedClient.java#L35) but [client creates WebTarget base](https://github.com/yahoo/athenz/blob/master/clients/java/zms/src/main/java/com/yahoo/athenz/zms/ZMSRDLGeneratedClient.java#L20) in constructor.

### zms_java_client
- athenz.zms.client.read_timeout
- athenz.zms.client.connect_timeout

https://github.com/yahoo/athenz/blob/master/clients/java/zms/src/main/java/com/yahoo/athenz/zms/ZMSClient.java#L287-L288

### zts_java_client
- athenz.zts.client.read_timeout
- athenz.zts.client.connect_timeout

https://github.com/yahoo/athenz/blob/master/clients/java/zts/src/main/java/com/yahoo/athenz/zts/ZTSClient.java#L358-L359

Since it's RDLGenerated codes, ardielle-tools should be fixed so I made a PR https://github.com/ardielle/ardielle-tools/pull/90

After this PR is merged, I'd like to request for re-generating the clients.

**Comment by havetisyan** [comment]
Chris,

#307 should address this issue though we took a different approach. Since we need to set the tls object for a client, it was more flexlible to create a Client object and pass that to the generated code rather than createing a new base object every time a property is set.

**Comment by tatyano** [comment]
Looks like a better idea.
Thank you.
