### ISSUE TITLE
host Athenz start page  under https://

### ISSUE THREAD

**Issue by dmitris** [yahoo/athenz#277]
The current info site is available only as http:// URL http://www.athenz.io/ and stumbling into https://www.athenz.io does not look good; would it be possible to get a certificate for the domain (ex. from https://letsencrypt.org/) and migrating the site to the https:// URL?  Maybe it would be possible to do a Kubernetes cluster based setup similar to what CD did https://github.com/screwdriver-cd/guide/pull/115 to fix https://github.com/screwdriver-cd/screwdriver/issues/748?

![screen shot 2017-10-10 at 11 22 12 am](https://user-images.githubusercontent.com/31205/31381627-601b5d58-adb5-11e7-83a6-079fc8d67c56.png)

@havetisyan

**Comment by tatyano** [comment]
@havetisyan 
It seems that the site is already available as https:// URL. Should this ticket be closed?

**Comment by mujibur** [comment]
yes. this can be closed. migrated the site to use https (https://www.athenz.io)
