### ISSUE TITLE
[Java] Remove static settings configured via System properties.

### ISSUE THREAD

**Issue by manolama** [yahoo/athenz#335]
I noticed a number of settings are configured through system properties, e.g. the `ZTS_CLIENT_PROP_X509CSR_DOMAIN` property that's set as a static variable in the library. This will be a big issue for users down the road, for example, if a single JVM needs to talk to different Athenz installations, they can't do it if one installation uses value A for the CSR domain and installation B uses something else. We ran into the same issue with Zookeeper. Don't fall into the same pit please.

**Comment by havetisyan** [comment]
Thanks @manolama for the feedback. The specific mentioned property is an optional one and can be ignored (you would pass the full value in the cloud argument). However, that would be confusing, so I added additional helper method where you can specify the csr domain/dn values directly as opposed to relying on system properties.

#380
