### ISSUE TITLE
athenz-auth-core is not in maven central

### ISSUE THREAD

**Issue by wcpan** [yahoo/athenz#366]
I'm trying to use sia inside java, but couldn't find athenz-auth-core, can you help to fix this.

https://github.com/yahoo/athenz/blob/master/docs/dev_centralized_access.md
https://mvnrepository.com/search?q=athenz

thanks.

**Comment by havetisyan** [comment]
For now our libraries are only available from Bintray repository. Please take a look at the full java example documentation for centralized access:

https://github.com/yahoo/athenz/blob/2bb23838e09eda7d8ec67cace14dddcbe8fb6a49/docs/example_java_centralized_access.md#client-project-dependency-update
