### ISSUE TITLE
The e-mail address of the athenz code owner?

### ISSUE THREAD

**Issue by fuwei123456** [yahoo/athenz#386]
Hi,
I'm Fuwei from 360 CodeSafe Team. We found some weaknesses/bugs in athenz using our static analysis tools and I want to send the more detailed information to the code owner.

I don't know whether it is appropriate here to ask this question. If it is not suitable, please forgive me. E-mail address can be sent to fuwei@360.net.

Thank you!
360 CodeSafe

**Comment by havetisyan** [comment]
I responded to your email privately.
