### ISSUE TITLE
Changing the type of TemplateParam value from SimpleName to CompoundName

### ISSUE THREAD

**Issue by tatyano** [yahoo/athenz#394]
For now, the type definition of [TemplateParam value](https://github.com/yahoo/athenz/blob/master/core/zms/src/main/rdl/Template.tdl#L25) is [SimpleName](https://github.com/yahoo/athenz/blob/master/core/zms/src/main/rdl/Names.tdl#L9).
To input subdomains or resource groups, I think it's better to have it be [CompoundName](https://github.com/yahoo/athenz/blob/master/core/zms/src/main/rdl/Names.tdl#L12).

By thinking of compatibilities, is it possible for you to consider changing the type definition in rdl?

**Comment by havetisyan** [comment]
Yes, should be no problem. It was primarily done for services which are SimpleNames but if you want a template that might include subdomains in resource values then we can extend the value to be CompoundName.
