### ISSUE TITLE
The latest docker image hasn't been uploaded to Docker Hub

### ISSUE THREAD

**Issue by tatyano** [yahoo/athenz#398]
According to [the log of the latest build](https://travis-ci.org/yahoo/athenz/builds/333390434), there has been an error while publishing the docker image.
```
docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```
I assume that the username or the password set to the env are wrong.
Could you check the values just in case?

**Comment by havetisyan** [comment]
That was actually done to test some stuff out and left out on purpose. Unfortunately, if you look at the earlier releases, the overall build with aws and docker images and pushes, takes too long and travis terminates our job as it exceeds allowed time. So I'm thinking about possible ways of breaking up the jobs but haven't had a chance to spend much time on this task.

**Comment by tatyano** [comment]
@havetisyan Hi Henry,

Thank you for the answer.
I wasn't thinking about the allowed time.

Should I close this issue?
Perhaps, we can just leave this until we eventually take some actions for it.

Thank you,
Chris
