### ISSUE TITLE
Should ZTS verify the IP address of the instance which is calling postInstanceRefreshInformation

### ISSUE THREAD

**Issue by tatyano** [yahoo/athenz#422]
Regarding to #421, I wondered if ZTS should check the remote IP address of instance when postInstanceRefreshInformation API is called. (This idea only suits to the case of b).)

> a) AWS - you must submit a temp credentials for the athenz role you assume. those credentials are valid for max 1 hour only. So if you copied the temp credentials, you can't refresh after 1 hour.
> b) Openstack - the provider verifies using nova api that the instance (identified by its uuid) is still running thus you cannot have an instance that is no longer active asking for a refresh.

The IP address of the instance can be set in an attestation data by the provider with a signature so ZTS can verify the signature first, then compare the IP address in the attestation data with the IP address of the requester.
Although this feature should probably be optional even if it is doable.

Please let me know your opinion about this.

Thank you,
Chris

**Comment by havetisyan** [comment]
ZTS server does not know how to process the attestation data. It's something that the provider understands. So it's up to the provider to validate the IP address. This is why if you look at the implementation of the generateInstanceConfirmObject method in the ZTSImpl, ZTS tells the provider what is the client IP address where it received the request, so it's up to the provider to validate that.

**Comment by tatyano** [comment]
I was missing the flows implemented below:
https://github.com/yahoo/athenz/blob/5276348abf540589dff29131bc56683b6f7bf716/servers/zts/src/main/java/com/yahoo/athenz/zts/ZTSImpl.java#L1880

Many thanks to your speedy answers.

Thank you,
Chris
