### ISSUE TITLE
athenz ui using outdated debug package

### ISSUE THREAD

**Issue by havetisyan** [yahoo/athenz#486]
The package.json file for Athenz UI contains a dependency for debug version 2.2.0. Versions of debug below 2.6.8 may be vulnerable to a regular expression denial of service.

Update the version of debug used by the application to the latest stable and secure version available. The latest version of debug is version 3.1.0.32 In the package.json dependencies, require that a version of debug be greater than 2.6.9, if using the 2.6.x series, or greater than 3.1.0.

@tatyano can you also take a look at this one. thanks.

**Comment by tatyano** [comment]
We'll take a look. thank you.
