### ISSUE TITLE
KeyRefresher is not shutting down until the sleep time is reached (default: 60 mins)

### ISSUE THREAD

**Issue by scw1109** [yahoo/athenz#543]
As a library user, I would like to control the shutdown of the KeyRefresher at the moment I call it.
Therefore, similar to the pattern of the Executors interface from JDK, Athenz should provide a `shutdownNow()` method to force the shutdown of KeyRefresher immediately.

Otherwise, the behavior of the application would look wired as default it would blocked for 60 mins until the thread sleep ends.

**Comment by havetisyan** [comment]
shutdown() instead of just setting the flag it now also interrupt the keyrefresher thread which will cause it to exit.
