### ISSUE TITLE
ZTSClient should closing all resource when close method called

### ISSUE THREAD

**Issue by scw1109** [yahoo/athenz#544]
Currently, the Timer for prefetcher is not close when the method called.
Which it should be.

**Comment by havetisyan** [comment]
Prefetcher is a static Timer based implementation and not tied to any ZTSClient instance. So a close method for a ZTSClient instance should not affect the prefetcher. There is a removePrefetcher api call which is not exposed as public unfortunately but handles cancelling the prefetcher task. We should probably just rename that method and expose it as public.

**Comment by havetisyan** [comment]
You can now call ZTSClient.cancelPrefetch() to stop the prefetcher. This should be called before application shutdown.
