### ISSUE TITLE
Slack access

### ISSUE THREAD

**Issue by mnaser** [yahoo/athenz#596]
Hi everyone:

It looks like there is a Slack channel however an invite is required to access?  Is there a link that should be setup for that?

Thanks,
Mohammed

**Comment by havetisyan** [comment]
Hi Mohammed,

Let me follow up to see how that slack channel was set up. 

Thanks,
Henry

**Comment by mnaser** [comment]
Hi @havetisyan -- I'm sure you've been busy but do you know if we can get an update on this? :)

**Comment by havetisyan** [comment]
Hi Mohammed,
I’m still trying to follow up with another team at Oath that has a product opensourced and has setup public access to their slack workspace to see what is the work involved. 
However, if you have any questions about Athenz I’d suggest to follow with us in our athenz-users google group and we’ll be happy to help. 
ThanksHenry 

Sent from Yahoo Mail for iPhone


On Monday, November 26, 2018, 5:13 AM, Mohammed Naser <notifications@github.com> wrote:


Hi @havetisyan -- I'm sure you've been busy but do you know if we can get an update on this? :)

**Comment by havetisyan** [comment]
For my own info - need to implement something like https://slack.screwdriver.cd to send invites to the athenz slack channel.

**Comment by mujibur** [comment]
@mnaser we have updated the 'Contacts' page with slack invite link. Please check it out.
