### ISSUE TITLE
An select2 error when add a new policy

### ISSUE THREAD

**Issue by shermanrxie** [yahoo/athenz#632]
managePolicy.js:10 Uncaught TypeError: $(...).select2 is not a function
    at managePolicy.js:10
    at Object.12../common (managePolicy.js:80)
    at o (_prelude.js:1)
    at r (_prelude.js:1)
    at _prelude.js:1

**Comment by havetisyan** [comment]
Is this happening when you're adding a specific policy or just any policy?

**Comment by havetisyan** [comment]
Fixed in 1.8.20
