### ISSUE TITLE
bad TLS certificate for https://athenz.io

### ISSUE THREAD

**Issue by dmitris** [yahoo/athenz#650]
@mujibur following up on #227 - is there a compelling reason to have a proper certificate for https://www.athenz.io but not for https://athenz.io (see the screenshot)?
![Screen Shot 2019-03-22 at 11 28 35 AM](https://user-images.githubusercontent.com/31205/54816920-df32d780-4c95-11e9-9f2e-28639d88ed96.png)

**Comment by abvaidya** [comment]
should be working now. athenz.io gets redirected to www.athenz.io

**Comment by dmitris** [comment]
LGTM - thanks
