### ISSUE TITLE
setup_dev_ui.sh - 400 putServiceIdentity: Invalid/Reserved service name

### ISSUE THREAD

**Issue by rshermanTHG** [yahoo/athenz#657]
Whilst setting up a local athenz installation when running setup_dev_ui.sh it fails at the point that it registers the ui service with `400 putServiceIdentity: Invalid/Reserved service name`.

The offending line in the script is `$ROOT/bin/$HOST_PLATFORM/zms-cli -c $ROOT/keys/zms_cert.pem -z https://$ZMS_HOSTNAME:4443/zms/v1 -d athenz add-service ui 0 $ROOT/keys/athenz.ui_pub.pem` 

If I change the service name to something other than ui the error disappears. I then edited the zms data to rename the service back to ui and I could then create domains etc. via the ui.

This is with 1.8.18 of the zms service and with 1.8.10 of the zts and ui services all from bintray.

**Comment by havetisyan** [comment]
@rshermanTHG thanks for the report. We need to update the setup script/instructions to use a different name that ui since we no longer allow services that are 2 chars or less. We'll fix this.

**Comment by havetisyan** [comment]
Fixed in 1.8.20
