### ISSUE TITLE
Support metrics implementation

### ISSUE THREAD

**Issue by kevindiu** [yahoo/athenz#709]
For now, Athenz only has the implementation `NoOpMetric` to support metrics interface (which means no metric implementation is supported yet). 
Can we provide a new reference implementation for the metrics interface such as prometheus? It will not change default metrics implementation, user can choose which implementation they want.

**Comment by kevindiu** [comment]
We are working on supporting prometheus implementation and we will create an pull request for it.

**Comment by WindzCUHK** [comment]
@havetisyan 

The metric implementation for prometheus is as below:
https://github.com/WindzCUHK/athenz-metric-prometheus

Currently, it is working well as an external jar.
However, as it has dependency on prometheus client libraries,
should we keep it as separated repo, or include it in the Athenz repo?
https://github.com/WindzCUHK/athenz-metric-prometheus/blob/master/pom.xml#L46-L69
