### ISSUE TITLE
Docker Image is not tagged

### ISSUE THREAD

**Issue by stjohnjohnson** [yahoo/athenz#75]
There is only [one tag](https://hub.docker.com/r/athenz/athenz/tags/) on Docker Hub (latest).  There are [21 releases](https://github.com/yahoo/athenz/releases) on GitHub.

For teams that use automation for deploying Docker images, it's heavily recommended not to use latest to ensure consistency when scaling up nodes.

Can you please add tags for all releases?

**Comment by havetisyan** [comment]
Thanks @stjohnjohnson for your suggestion. The docker images are now tagged with their github release tags.
