### ISSUE TITLE
High res version of your logo

### ISSUE THREAD

**Issue by dankohn** [yahoo/athenz#752]
Could I please get a version of your logo in SVG, AI, or EPS format so that I can include this project in https://landscape.cncf.io/category=key-management&format=card-mode&grouping=category.

You need to zip it first to attach it here or you can just add it to https://github.com/yahoo/athenz/tree/master/docs/images.

**Comment by havetisyan** [comment]
Hi Dan,

https://github.com/yahoo/athenz/blob/master/docs/images/athenz-logo-stack.svg

Please let us know if that works,

Thanks,
Henry

**Comment by dankohn** [comment]
That was a little tricky because the SVG has other version of the logo outside of the viewport but I was able to resolve. Here it is: https://landscape.cncf.io/selected=athenz
