### ISSUE TITLE
Docker Image is not documented

### ISSUE THREAD

**Issue by stjohnjohnson** [yahoo/athenz#76]
https://hub.docker.com/r/athenz/athenz/ has no documentation.  Can you please populate it with content from https://github.com/yahoo/athenz/blob/master/docs/setup_docker.md

**Comment by charlesk40** [comment]
Just updated with documentation https://hub.docker.com/r/athenz/athenz/ Thanks

**Comment by stjohnjohnson** [comment]
Thanks!
