### ISSUE TITLE
Use a human readable time stamp as part of the ami name 

### ISSUE THREAD

**Issue by tchia04** [yahoo/athenz#80]
Instead of using "Athenz 1491517496" as the AMI name, it would be better to use something like "Athenz-20170406152456"

This is so that it's consistent with some of the popular AMI name such as 
amzn-ami-hvm-2017.03.0.20170417-x86_64-gp2 - ami-c58c1dd3
RHEL-7.3_HVM_GA-20161026-x86_64-1-Hourly2-GP2 - ami-b63769a1

**Comment by havetisyan** [comment]
Thanks @tchia04 for your suggestion. We're now generating the ami with a human readable time stamp: Athenz-2017-05-16T10_34_30.
