### ISSUE TITLE
Using 0.0.0.0/0 in the security group for port 22 is a very bad idea

### ISSUE THREAD

**Issue by tchia04** [yahoo/athenz#83]

**Comment by havetisyan** [comment]
Thanks Tony for you feedback.  We were trying not to introduce any concepts of security groups when just doing an evaluation of Athenz so we left the default AWS setting as is (even though AWS itself presents with a warning). We updated the documentation to point this out as well and the steps were updated to use the "My IP" option for the evaluation.
