### ISSUE TITLE
Feature Request: Helm chart for k8s deploy

### ISSUE THREAD

**Issue by z0r0** [yahoo/athenz#845]
Hello, This is a feature request for a helm chart for deployment of athenz on k8s. I'll be happy to give a first stab at the chart myself but I wanted to take a look here before getting started on it on my own.

**Comment by z0r0** [comment]
This would especially help when it comes to kicking the tires of using athenz to power the configuration of the istio custom resources through the athenz istio controller.

**Comment by WindzCUHK** [comment]
Hi @z0r0, thank you very much for posting the feature request.

I am Windz from Yahoo Japan Corporation. We also have the plan to support K8s deploy in the coming future, although we still haven't set the schedule yet.

I am currently working on the docker deployment of Athenz in production. It is still working in progress, but I think you would like to have more references.
https://github.com/WindzCUHK/athenz/blob/zms-on-external-IdP/docker/docs/Athenz-bootstrap.md

We are looking forward to your great work. Please feel free to contact us if you have any questions.

**Comment by z0r0** [comment]
My biggest question right now is with regards to hosting images at this time. It looks like the deployment steps are heavily biased to building images, while not providing an out of the box stable release to a registry like dockerhub. Are there plans to provisioning stable releases on a registry in the future? it'd make building helm charts a lot more attractive to people looking to kick the tires.

**Comment by WindzCUHK** [comment]
> Are there plans to provisioning stable releases on a registry in the future?

I totally agreed with you, but sorry that we still do not have a schedule to have official release for docker image currently.
Please free feel to upload the built docker image to any public registries you like, and use it in the helm charts. We can update the image URL later on, once we have the official release ready.

**Comment by WindzCUHK** [comment]
Just a sidetrack. I have updated the docker images recently.
Other than changing some ENV variables,
I also removed some unused images to speed up the build process. ([diff](https://github.com/WindzCUHK/athenz/pull/2/files?file-filters%5B%5D=No+extension))
