### ISSUE TITLE
Weak Cryptographic Hash

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [yahoo/athenz#891]
https://github.com/yahoo/athenz/blob/9b2f1202663455322037390be2feb02d7ca0b854/libs/java/cert_refresher/src/main/java/com/oath/auth/KeyRefresher.java#L39

Weak cryptographic hashes cannot guarantee data integrity and should not be used in security-critical contexts.

**Comment by havetisyan** [comment]
it is not used in a security critical context. It is just used to find out if a file has been changed or not.
